apiVersion: v1
kind: Service
metadata:
  name: mcp-api
  namespace: ai-zero-trust
spec:
  selector:
    app: mcp-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-api
  namespace: ai-zero-trust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-api
  template:
    metadata:
      labels:
        app: mcp-api
    spec:
      containers:
        - name: mcp-api
          image: khwajanawaz/mcp-api:v1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000
              name: http

          envFrom:
            - configMapRef:
                name: ai-zero-trust-config

            - secretRef:
                name: ai-zero-trust-secrets

          readinessProbe:
            httpGet:
              path: /openapi.json
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 6

          resources:
            requests:
              cpu: "100m"
              memory: "192Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
